# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27264a4f58fd2d591af14109ae6811e28bb999e161b1f23cfa3d39581c4aa10693d09d20d6ece1e3cc22e8e1c58b50bb86cd96e6f3efca5620a1bf4836593c2

test:
  secret_key_base: 68f082680951974b62f00106524454673204449cfc8285cda35ae3ee275bae0b169e13df862478b57b5ae7be88dbfc4b11ed7fb300859c4d6e33755f1767e76a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
