apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: drkiq
  name: drkiq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: drkiq
    spec:
      containers:
      - env:
        - name: SECRET_TOKEN
          value: asecuretokenwouldnormallygohere
        - name: WORKER_PROCESSES
          value: "1"
        - name: LISTEN_ON
          value: 0.0.0.0:8000
        - name: DATABASE_URL
          value: postgresql://drkiq:yourpassword@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000
        - name: CACHE_URL
          value: redis://redis:6379/0
        - name: JOB_WORKER_URL
          value: redis://redis:6379/0
        name: drkiq
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /drkiq
          name: .
      restartPolicy: Always
      volumes:
      - name: .
        persistentVolumeClaim:
          claimName: .
status: {}
