apiVersion: v1
kind: Secret
metadata:
  name: all-secret
type: Opaque
data:
    SECRET_TOKEN: "asecuretokenwouldnormallygohere"
    WORKER_PROCESSES: 1
    LISTEN_ON: 0.0.0.0:8000
    DATABASE_URL: postgresql://drkiq:yourpassword@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000
    CACHE_URL: redis://redis:6379/0
    JOB_WORKER_URL: redis://redis:6379/0
